### ISSUE TITLE
Invalid parameters: must provide an Ethereum address.

### ISSUE THREAD

**Issue by er3166** [HashLips/hashlips_nft_contract#38]
Everything was working fine, but the images where not showing up on opensea for the hidden image. Only during the reveal function. So I redid the contract and now I keep getting the error "Invalid parameters: must provide an Ethereum address.". I get this error when I try to mint 2 on another wallet as a test. I'm using rinkeby network, contract pause is set to false.  Correct contract is selected and metamask is showing the correct 2nd text wallet. For some reason I keep getting this error and it will not allow to make a transaction. I attempted with multiple wallets and still the same. Only the contract owner wallet address allows a second mind. Max mint is set to 2 and supply set to 4000. Ether is set at 0.02 and wei is doubled after getting it from calling the cost. I'm using the lower gas sol file. Had the same error on the flat file aswell. I'm using injected Web3 on Rinkeby. Someone please help, I dont know what i'm doing wrong, but I'm sure I am. Been going at it for days :(

**Comment by er3166** [comment]
I have also tried 3 different browsers (Chrome,Firefox & Edge)

**Comment by jiaxu09** [comment]
I have the same issue, did you manage to solve this problem?

**Comment by Yuceff** [comment]
same here

**Comment by glitch-r** [comment]
i am having similar issues, have you found a fix yet?

**Comment by jiaxu09** [comment]
It seems to the problem only happened in remix, I tested on polygonscan and dapp demo, everything works fine, no problem.
