### ISSUE TITLE
Can't copy bytecode in Remix.ethereum

### ISSUE THREAD

**Issue by Cyber710** [HashLips/hashlips_nft_contract#39]
Any help would be appreciated. I have been able to copy bytecode in the past, but for some reason, it is not working now. Can anyone help?

<img width="304" alt="Screen Shot 2022-02-02 at 10 56 49 AM" src="https://user-images.githubusercontent.com/98911376/152219622-a7d9d892-15a3-4cbb-a3ab-422a776cbc80.png">

**Comment by Cyber710** [comment]
I was able to solve the issue by opening remix.ethereum a new tab....

**Comment by DigiDrips** [comment]
Hey there quick question for ya, how'd you get the drop down next to "deploy" ? ive followed the video to the T yet dont have the option to get that drop down and have those fields.

Much appreciated
