### ISSUE TITLE
polygon remix.ethereum

### ISSUE THREAD

**Issue by emrebaran** [HashLips/hashlips_nft_contract#49]
![image](https://user-images.githubusercontent.com/98944150/157264683-7b7d8fa5-4217-4c52-9e50-1484197bfe44.png)
Hey guys! I want to mint my collection with polygon to opensea. I tested that with the rinkeby network. That worked but its not working on the polygon network. Any Idea what i am doing wrong? Thank you for your help

**Comment by enescaakir** [comment]
What error are you getting?

**Comment by emrebaran** [comment]
When i click on transact, metamask is not popping up and remix says that transaction may fail... I forced the transaction and it failed...

**Comment by enescaakir** [comment]
Can you paste error here

**Comment by emrebaran** [comment]
![image](https://user-images.githubusercontent.com/98944150/157620368-21b13f18-c0e4-4321-92c7-06cb6aef8956.png)
Thank you for your help

**Comment by enescaakir** [comment]
Since you are the contract owner, you may need to mint the value by leaving it blank or if you are trying with another account there is not enough balance in the wallet. First red line is your balance second line you're sending value

![image](https://user-images.githubusercontent.com/49621993/157621865-d24f8cb2-9b1e-4c4d-a976-87a643224737.png)

**Comment by emrebaran** [comment]
so that worked, thank you but now iam getting a new error..
![image](https://user-images.githubusercontent.com/98944150/157624643-0c27e44a-2764-4ced-af67-efcda17f7ada.png)

**Comment by enescaakir** [comment]
1. Check paused value
2. Mint less than 50 amount
3. If those not works paste here contract address and contract code

**Comment by emrebaran** [comment]
Ahh if fixed it .. i got the wrong adress... i found the right adress at polygonscan.

Thank your big help man... :)

**Comment by enescaakir** [comment]
I'm glad we solved it! Good works ✋🏻

**Comment by emrebaran** [comment]
Thank you again Enes tesekürler :)

**Comment by enescaakir** [comment]
Dont forget close the issue, rica ederim 😄
