### ISSUE TITLE
No images on Rinkeby and Opensea

### ISSUE THREAD

**Issue by TriLogic** [HashLips/hashlips_nft_contract#56]
Generated images and JSON, updated everything according to the video instructions and deployed the contract according to the instructions.  Contract is out there running on Rinkeby but no images show up on the OpenSea.io test site. No hidden image, no NFT image, nothing.  Would love to take my collection live but I don't trust the contract.

I'd pay someone good money to help me get this project over  the finish line.

**Comment by cryptocraig-nft** [comment]
Open one of the .json files, check it says: "image": "ipfs://__YOUR__CID__/1.png", 
I had the same issue, I had deleted the IPFS:// part. 
Just an idea, I'm definitely no expert! ;)
Good luck

**Comment by TriLogic** [comment]
I've found that although the hidden metadata is correct on the contract the baseUri for revealed data has to be set after the fact.  Not sure why this is.  Also the missing images are generally that OpenSea test is mind bogglingly slow.

**Comment by vipdiv** [comment]
> I've found that although the hidden metadata is correct on the contract the baseUri for revealed data has to be set after the fact. Not sure why this is. Also the missing images are generally that OpenSea test is mind bogglingly slow.

Can you comment on exactly how slow it is? And can you comment further on _baseUri for revealed data has to be set after the fact_ ?

Thanks
